### ISSUE TITLE
Can´t get an output video format.

### ISSUE THREAD

**Issue by Crissmore** [Gericom/FastVideoDSEncoder#1]
Was trying to covert to .fv some videos but i don´t get any output.fv file, i´m following the guide wich is just a drag and drop on the .bat file. 
Update: Figured what was going on.

**Comment by calcgirl45** [comment]
What was going wrong? I have the same problem but haven't figured out what's wrong?

**Comment by PrgmrAtHrt** [comment]
> What was going wrong? I have the same problem but haven't figured out what's wrong?

It sounds like his processor doesn't support AVX2 and yours doesn't either. I also have the same issue which is why I mentioned it on discord and said information was added to the wiki. We'll just have to hope the author adds SSE support.

**Comment by calcgirl45** [comment]
Turns out I just didn't have .net installed, after that it worked.

**Comment by Crissmore** [comment]
Yes i had to go testing wich one was suited for the job. But it got solved once i instaled the right one.
